#!/bin/bash
set -e

mysql=("$@")

MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-magento}
MYSQL_DATABASE=${MYSQL_DATABASE:-magento}
MYSQL_USER=${MYSQL_USER:-magento}
MYSQL_PASSWORD=${MYSQL_PASSWORD:-magento}

"${mysql[@]}" <<-EOSQL
  ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
  CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED WITH mysql_native_password BY '${MYSQL_PASSWORD}';
  GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_USER}'@'%' WITH GRANT OPTION;
  FLUSH PRIVILEGES;
EOSQL

if [ -n "$MYSQL_DATABASE" ]; then
  echo "Creating database ${MYSQL_DATABASE}"
  "${mysql[@]}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS \`$MYSQL_DATABASE\` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    GRANT ALL PRIVILEGES ON \`$MYSQL_DATABASE\`.* TO '${MYSQL_USER}'@'%';
    FLUSH PRIVILEGES;
EOSQL
fi
